name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [3.1.100]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore local tools
        run: dotnet tool restore
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy
        run: dotnet fake run build.fsx -t DeployServer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZ_USER_NAME: ${{ secrets.AZ_USER_NAME }}
          AZ_RESOURCE_GROUP: ${{ secrets.AZ_RESOURCE_GROUP }}
          AZ_TENANT: ${{ secrets.AZ_TENANT }}
          AZ_FUNCTIONAPP: ${{ secrets.AZ_FUNCTIONAPP }}
          AZ_SERVERFARM: ${{ secrets.AZ_SERVERFARM }}
          AZ_APPINSIGHTS: ${{ secrets.AZ_APPINSIGHTS }}
          AZ_STORAGE: ${{ secrets.AZ_STORAGE }}
          AZ_CORS: ${{ secrets.AZ_CORS }}